<?xml version="1.0"?>
<package format="2">
  <name>autotrans_logger</name>
  <version>0.0.0</version>
  <description>Baseline runtime logger for AutoTrans experiments.</description>

  <maintainer email="todo@example.com">AutoTrans Maintainer</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>rospy</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>mavros_msgs</depend>
  <depend>quadrotor_msgs</depend>

  <exec_depend>rospkg</exec_depend>

  <export>
  </export>
</package>
